#!/bin/bash
### BEGIN INIT INFO
# Provides: scripts
# Default-Start: 2 3 4 5
# Default-Stop? 0 1 6
# Short-Description: Shell Script Manager
# Description: Shell Script Sync and Download Service provided by daemon.
### END INIT INFO

localdir=/etc/.scripts
logfile=/var/log/scripts.log
user=lxadmin
pass=keDBD6V4chcG
srvaddr=empresa.srv
share=LXVOL

CLEAN() {
   rm -R $localdir/* >> $logfile
}

SETEXEC() {
   echo "`date` - Setting permissions" >> $logfile
   cd $localdir/sh
   find . -type f -name "*.sh" -exec chmod +x {} \;
}

SRVON() {
   if ! ping -c 2 $srvaddr >/dev/null; then
      echo "`date` - Server DOWN!!! Temporary files will not be erased" >> $logfile
   else
      echo "`date` - Server UP!!! Cleaning temporary files" >> $logfile
      CLEAN
   fi
}

DOWNLOAD() {
   echo "`date` - Downloading ALL scripts" >> $logfile
   smbclient -U $user%$pass //$srvaddr/$share -c 'prompt;recurse;lcd /etc/.scripts/;mget *' >> $logfile
}

EXECUTE() {
   echo "`date` - Running all scripts" >> $logfile
   cd $localdir/sh
   find . -type f -name "*.sh" -exec {} \; >> $logfile
}

SRVON
DOWNLOAD
SETEXEC
EXECUTE

echo -e "`date` - End of execution\n" >> $logfile